import {useCallback,useEffect,useRef,useState,type ChangeEvent,type DragEvent,type PointerEvent as ReactPointerEvent} from "react";
import {ChevronLeft,ChevronRight,Download,FilePlus2,Highlighter,MousePointer2,PenLine,Redo2,RotateCw,Square,Type,Undo2,ZoomIn,ZoomOut} from "lucide-react";
import {createPdfEngine,type PageInfo} from "@paperless/pdf-engine";import {normalizeRect,type Overlay,type Tool} from "@paperless/editor-core";import {useEditor} from "./store";
const tools:{id:Tool;label:string;Icon:typeof MousePointer2}[]=[{id:"select",label:"Select",Icon:MousePointer2},{id:"text",label:"Add text",Icon:Type},{id:"ink",label:"Draw",Icon:PenLine},{id:"rect",label:"Rectangle",Icon:Square},{id:"redact",label:"Redact",Icon:Highlighter}];
type OpenDoc={name:string,bytes:ArrayBuffer,pages:PageInfo[],urls:Map<string,string>};
export function App(){const engine=useRef<ReturnType<typeof createPdfEngine>|null>(null);const [open,setOpen]=useState<OpenDoc|null>(null);const [image,setImage]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const {tool,zoom,page,doc,undo,redo,setTool,setZoom,setPage,execute,undoOnce,redoOnce,reset}=useEditor();
 useEffect(()=>{engine.current=createPdfEngine();return()=>engine.current?.terminate()},[]);
 const load=useCallback(async(file:File)=>{if(file.type!=="application/pdf"&&!file.name.toLowerCase().endsWith(".pdf")){setError("Choose a PDF file.");return}setBusy(true);setError("");try{const bytes=await file.arrayBuffer();const meta=await engine.current!.api.loadDocument(bytes.slice(0));setOpen({name:file.name,bytes,pages:meta.pages,urls:new Map()});reset()}catch(e){setError(e instanceof Error?e.message:"This PDF could not be opened.")}finally{setBusy(false)}},[reset]);
 const openBytes=open?.bytes;
 useEffect(()=>{if(!openBytes)return;let active=true;setBusy(true);engine.current!.api.renderPage(page,Math.min(2.2,window.devicePixelRatio*zoom)).then(png=>{if(!active)return;const key=`${page}-${zoom}`;const copy=new Uint8Array(png.byteLength);copy.set(png);const url=URL.createObjectURL(new Blob([copy.buffer],{type:"image/png"}));setOpen(current=>{if(!current)return current;const old=current.urls.get(key);if(old)URL.revokeObjectURL(old);return {...current,urls:new Map(current.urls).set(key,url)}});setImage(url)}).catch(e=>setError(e instanceof Error?e.message:"Page render failed")).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[openBytes,page,zoom]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();if(e.shiftKey)redoOnce();else undoOnce()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redoOnce()}if(e.key==="PageDown"&&open)setPage(Math.min(open.pages.length-1,page+1));if(e.key==="PageUp")setPage(Math.max(0,page-1))};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[open,page,redoOnce,setPage,undoOnce]);
 const pick=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(file)void load(file)};const drop=(e:DragEvent)=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)void load(file)};
 if(!open)return <main className="home" onDragOver={e=>e.preventDefault()} onDrop={drop}><header className="brand"><span className="mark">P</span><b>Paperless</b><span className="local">Local only</span></header><section className="hero"><p className="eyebrow">PRIVATE BY DEFAULT</p><h1>Edit the PDF.<br/><em>Keep the document.</em></h1><p>Open, review, and mark up PDFs without an account, an upload, or a paywall.</p><label className="openButton"><FilePlus2/>Open a PDF<input aria-label="Open PDF" type="file" accept="application/pdf,.pdf" onChange={pick}/></label><p className="dropcopy">or drop a PDF anywhere</p>{busy&&<p role="status">Opening securely on this device…</p>}{error&&<p className="error" role="alert">{error}</p>}</section><footer>AGPL-3.0 · No uploads · No analytics</footer></main>;
 const current=doc.overlays.filter(item=>item.page===page);const pageInfo=open.pages[page]!;const edited=doc.overlays.length>0||Object.keys(doc.rotations).length>0;
 const download=()=>{if(edited)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([open.bytes],{type:"application/pdf"}));a.download=open.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 return <div className="app"><header className="top"><div className="file"><span className="mark">P</span><div><b>{open.name}</b><small>{open.pages.length} pages · stored locally</small></div></div><div className="history"><button aria-label="Undo" disabled={!undo.length} onClick={undoOnce}><Undo2/></button><button aria-label="Redo" disabled={!redo.length} onClick={redoOnce}><Redo2/></button></div><button className="export" disabled={edited} title={edited?"Edited PDF export is not enabled yet; your original will never be mislabeled as edited.":"Download original PDF"} onClick={download}><Download/> {edited?"Export pending":"Download"}</button></header><div className="work"><aside className="rail"><div className="railTitle"><b>Pages</b><span>{open.pages.length}</span></div>{open.pages.map((_,i)=><button key={i} className={i===page?"thumb active":"thumb"} onClick={()=>setPage(i)}><span>{i+1}</span><div>Page {i+1}</div></button>)}</aside><main className="canvasArea"><nav className="tools" aria-label="Editing tools">{tools.map(({id,label,Icon})=><button key={id} className={tool===id?"chosen":""} aria-pressed={tool===id} onClick={()=>setTool(id)}><Icon/><span>{label}</span></button>)}<span className="divide"/><button onClick={()=>execute({type:"rotate",page,before:doc.rotations[page]??0,after:(doc.rotations[page]??0)+90})}><RotateCw/><span>Rotate</span></button></nav><div className="stage">{busy&&<div className="loading">Rendering page…</div>}<PageCanvas image={image} info={pageInfo} zoom={zoom} rotation={doc.rotations[page]??0} overlays={current} tool={tool} onAdd={overlay=>execute({type:"add",overlay})} page={page}/></div><div className="status"><div><button onClick={()=>setPage(Math.max(0,page-1))} disabled={page===0}><ChevronLeft/></button><span>{page+1} / {open.pages.length}</span><button onClick={()=>setPage(Math.min(open.pages.length-1,page+1))} disabled={page===open.pages.length-1}><ChevronRight/></button></div><div><button aria-label="Zoom out" onClick={()=>setZoom(zoom-.15)}><ZoomOut/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(zoom+.15)}><ZoomIn/></button></div></div></main></div>{error&&<div className="toast" role="alert">{error}</div>}</div>
}
function PageCanvas({image,info,zoom,rotation,overlays,tool,onAdd,page}:{image:string|null;info:PageInfo;zoom:number;rotation:number;overlays:Overlay[];tool:Tool;onAdd:(o:Overlay)=>void;page:number}){const ref=useRef<HTMLDivElement>(null);const start=useRef<{x:number;y:number}|null>(null);const points=useRef<{x:number;y:number}[]>([]);const pos=(e:ReactPointerEvent)=>{const r=ref.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}};const down=(e:ReactPointerEvent)=>{if(tool==="select")return;ref.current?.setPointerCapture(e.pointerId);start.current=pos(e);points.current=[start.current];if(tool==="text"){const text=prompt("Text to add");if(text)onAdd({id:crypto.randomUUID(),page,kind:"text",x:start.current.x,y:start.current.y,text,size:18,color:"#171714"});start.current=null}};const move=(e:ReactPointerEvent)=>{if(tool==="ink"&&start.current)points.current.push(pos(e))};const up=(e:ReactPointerEvent)=>{if(!start.current)return;const end=pos(e);if(tool==="ink"&&points.current.length>1)onAdd({id:crypto.randomUUID(),page,kind:"ink",points:points.current,color:"#d64b35",width:3});if(tool==="rect"||tool==="redact"){const r=normalizeRect(start.current,end);if(r.width>.01&&r.height>.01)onAdd({id:crypto.randomUUID(),page,kind:tool,...r,color:tool==="redact"?"#111":"#d64b35"})}start.current=null;points.current=[]};return <div className="pageWrap" style={{width:info.width*zoom,height:info.height*zoom,transform:`rotate(${rotation}deg)`}}><div ref={ref} className={`page tool-${tool}`} onPointerDown={down} onPointerMove={move} onPointerUp={up}>{image&&<img src={image} alt={`Rendered PDF page ${page+1}`} draggable={false}/>}<svg className="overlay" viewBox="0 0 1 1" preserveAspectRatio="none">{overlays.map(o=>o.kind==="ink"?<polyline key={o.id} points={o.points.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={o.color} strokeWidth={o.width/Math.max(info.width,info.height)} vectorEffect="non-scaling-stroke"/>:o.kind==="rect"||o.kind==="redact"?<rect key={o.id} x={o.x} y={o.y} width={o.width} height={o.height} fill={o.kind==="redact"?o.color:"transparent"} stroke={o.color} strokeWidth="0.003"/>:null)}</svg>{overlays.filter((o):o is Extract<Overlay,{kind:"text"}>=>o.kind==="text").map(o=><span key={o.id} className="textOverlay" style={{left:`${o.x*100}%`,top:`${o.y*100}%`,fontSize:o.size*zoom,color:o.color}}>{o.text}</span>)}</div></div>}
